Class {
	#name : #JbIfElseNode,
	#superclass : #JbIfNode,
	#instVars : [
		'falseStatements'
	],
	#category : #'Jauburn-AST-Core'
}

{ #category : #'as yet unclassified' }
JbIfElseNode >> executeIn: environment [ 

	(condition evaluateIn: environment)
		ifTrue: [ ^trueStatements do: [ :e | e executeIn: environment  ] ]
		ifFalse: [ ^falseStatements do: [ :e | e executeIn: environment  ] ]
]

{ #category : #accessing }
JbIfElseNode >> falseStatements [
	^ falseStatements
]

{ #category : #accessing }
JbIfElseNode >> falseStatements: anObject [
	falseStatements := anObject
]
